# Generated by Django 4.2 on 2023-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='sample2')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='sample1')),
                ('saled', models.IntegerField(blank=True, null=True, verbose_name='sample1')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '会計データ',
                'db_table': '会計データの一覧',
            },
        ),
    ]
