# Generated by Django 4.2 on 2023-10-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodact_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名')),
                ('P_price', models.IntegerField(blank=True, null=True, verbose_name='商品の値段')),
            ],
            options={
                'verbose_name_plural': '商品に関するデータ一覧',
                'db_table': '商品に関するデータ一覧',
            },
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録時間'),
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='売れた個数'),
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='saled',
            field=models.IntegerField(blank=True, null=True, verbose_name='売れた値段'),
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_prodact_name', to='AppPOS.prodact_name'),
        ),
    ]
