# Generated by Django 4.2 on 2023-10-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_prodact_name_alter_accounting_data_c_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting_data',
            options={'verbose_name_plural': '会計データ一覧'},
        ),
    ]
