# Generated by Django 3.2.22 on 2023-10-20 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0003_alter_accounting_data_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_data',
            name='c_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録時間'),
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='売れた個数'),
        ),
        migrations.AlterField(
            model_name='accounting_data',
            name='saled',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='売れた値段'),
        ),
    ]
